# Generated by Django 5.0.7 on 2024-08-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localfood_app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_name',
        ),
    ]
