# Generated by Django 5.0.7 on 2024-08-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localfood_app', '0004_remove_productimage_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
